# Generated by Django 4.1 on 2022-10-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_alter_customuser_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[(1, 'Admin'), (2, 'Editor'), (3, 'User')], default=3, max_length=100, null=True),
        ),
    ]
