# Generated by Django 4.1 on 2022-10-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_alter_customuser_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('A', 'ADMIN'), ('B', 'EDITOR'), ('C', 'USER')], default='C', max_length=100),
        ),
    ]
